server:
  port: 8080
spring:
  application: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/pai-pai?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
# mybatis 相关统一配置
mybatis-plus:
  configuration:
    #开启下划线转驼峰
    map-underscore-to-camel-case: true
