server:
  port: 8080
spring:
  application: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/pai-pai?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
# mybatis 相关统一配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #配置日志打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启下划线转驼峰
    map-underscore-to-camel-case: true
    #配置逻辑删除
    global-config:
      db-config: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
